# Generated by Django 5.1.2 on 2024-11-04 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=20)),
                ('rol', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('modalidad', models.CharField(max_length=50)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='api.agenda')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='api.tipoevento')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultad', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('zona_horaria', models.CharField(max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docente', to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ComandoVoz',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_uso', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandos_voz', to='api.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='api.usuario'),
        ),
    ]
